dist: trusty
sudo: required

language: bash

before_install:
  # Add more modern repos
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository ppa:brightbox/ruby-ng -y
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"

  # Update sources
  - sudo apt-get update -qq

  # Install
  - sudo apt-get install -qq ruby2.1 ruby-switch
  - sudo ruby-switch --set ruby2.1

  - sudo apt-get install -qq shellcheck moreutils nodejs npm php5
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - sudo npm install -g eslint
  - sudo npm install -g jsonlint
  - sudo npm install -g mdlint
  - sudo gem install scss_lint

  # Install scripts
  - ./configure
  - sudo make install


script:

  # Validate coding guidelines of self
  - shellcheck --exclude=SC1090,SC2001 --shell=bash bin/*

  # Output Info
  - bin/file-crlf --info
  - bin/file-empty --info
  - bin/file-trailing-newline--info --info
  - bin/file-trailing-single-newline --info
  - bin/file-trailing-space --info
  - bin/file-utf8 --info
  - bin/file-utf8-bom --info
  - bin/git-conflicts --info
  - bin/git-ignored --info
  - bin/inline-css --info
  - bin/inline-js --info
  - bin/regex-grep --info
  - bin/regex-perl --info
  - bin/syntax-bash --info
  - bin/syntax-css --info
  - bin/syntax-js --info
  - bin/syntax-json --info
  - bin/syntax-markdown --info
  - bin/syntax-perl --info
  - bin/syntax-php --info
  - bin/syntax-python --info
  - bin/syntax-ruby --info
  - bin/syntax-scss --info
  - bin/syntax-sh --info


  # Test the scripts in dry mode
  - bin/file-crlf --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-empty --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-trailing-newline --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-trailing-single-newline --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-trailing-space --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-utf8 --path=. --config=etc/awesome-ci.conf --dry
  - bin/file-utf8-bom --path=. --config=etc/awesome-ci.conf --dry
  - bin/git-conflicts --path=. --config=etc/awesome-ci.conf --dry
  - bin/git-ignored --path=. --dry
  - bin/inline-css --path=. --config=etc/awesome-ci.conf --dry
  - bin/inline-js --path=. --config=etc/awesome-ci.conf --dry
  - bin/regex-grep --path=. --config=etc/awesome-ci.conf --dry
  - bin/regex-perl --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-bash --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-css --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-js --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-json --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-markdown --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-perl --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-php --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-python --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-ruby --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-scss --path=. --config=etc/awesome-ci.conf --dry
  - bin/syntax-sh --path=. --config=etc/awesome-ci.conf --dry

  # Test the scripts in real mode
  - bin/file-crlf --path=. --config=etc/awesome-ci.conf
  - bin/file-empty --path=. --config=etc/awesome-ci.conf
  - bin/file-trailing-newline --path=. --ignore=".git,configure.in" --config=etc/awesome-ci.conf
  - bin/file-trailing-single-newline --path=. --ignore=".git,configure.in" --config=etc/awesome-ci.conf
  - bin/file-trailing-space --path=. --ignore=".git,configure.in" --config=etc/awesome-ci.conf
  - bin/file-utf8 --path=. --config=etc/awesome-ci.conf
  - bin/file-utf8-bom --path=. --config=etc/awesome-ci.conf
  - bin/git-conflicts --path=. --config=etc/awesome-ci.conf
  - bin/git-ignored --path=.
  - bin/inline-css --path=. --config=etc/awesome-ci.conf
  - bin/inline-js --path=. --config=etc/awesome-ci.conf
    #- bin/regex-grep --path=. --config=etc/awesome-ci.conf
    #- bin/regex-perl --path=. --config=etc/awesome-ci.conf
  - bin/syntax-bash --path=. --config=etc/awesome-ci.conf
  - bin/syntax-css --path=. --config=etc/awesome-ci.conf
  - bin/syntax-js --path=. --config=etc/awesome-ci.conf
  - bin/syntax-json --path=. --config=etc/awesome-ci.conf
  - bin/syntax-markdown --path=. --config=etc/awesome-ci.conf
  - bin/syntax-perl --path=. --config=etc/awesome-ci.conf
  - bin/syntax-php --path=. --config=etc/awesome-ci.conf
  - bin/syntax-python --path=. --config=etc/awesome-ci.conf
  - bin/syntax-ruby --path=. --config=etc/awesome-ci.conf
  - bin/syntax-scss --path=. --config=etc/awesome-ci.conf
  - bin/syntax-sh --path=. --config=etc/awesome-ci.conf
