###
### Choose OS
###
sudo: required
dist: trusty


###
### Choose Environment
###
language: ruby
rvm: 2.5.0


###
### Install dependencies
###
before_install:
  # Add more modern repos
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y install python-software-properties; then break; else i=$((i+1)); fi done
  - sudo add-apt-repository -y ppa:brightbox/ruby-ng
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"

  # Install dependencies
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get update; then break; else i=$((i+1)); fi done
  - max=100; i=0; while [ $i -lt $max ]; do if sudo apt-get -y install
        gcc
        gcc-multilib
        make
        ruby2.5
        ruby2.5-dev
        ruby-switch
        moreutils
        shellcheck
        moreutils
        php5-cli
        dos2unix;
        then break; else i=$((i+1)); fi done

  # Set ruby version
  - ruby-switch --list
  - sudo ruby-switch --set ruby2.5
  - ruby -v
  - gem -v
  #
  #  - sudo gem update bundler
  #  - sudo gem pristine executable-hooks --version 1.3.2
  #  - sudo gem pristine gem-wrappers --version 1.3.2
  #  - sudo gem pristine nokogiri --version 1.8.1
  #  - sudo gem pristine ffi --version 1.9.25

  # Create custom source/bin directory
  - sudo mkdir -p /usr/local/bin
  - sudo mkdir -p /usr/local/src

  # NodeJS4
  - VERSION="$( curl -Lq https://nodejs.org 2>/dev/null | grep LTS | grep -Eo 'data-version.*.' | grep -oE 'v[0-9.]+' )"
  - sudo wget -P /usr/local/src https://nodejs.org/dist/${VERSION}/node-${VERSION}-linux-x64.tar.xz
  - sudo tar xvf /usr/local/src/node-${VERSION}-linux-x64.tar.xz -C /usr/local/src
  - sudo ln -s /usr/local/src/node-${VERSION}-linux-x64 /usr/local/node;
  - sudo ln -s /usr/local/node/bin/* /usr/local/bin/

  - sudo npm install -g eslint
  - sudo npm install -g jsonlint
  - sudo npm install -g mdlint
  - sudo gem install scss_lint
  - sudo gem install mdl

  # Symlink node binaries
  - sudo ln -s /usr/local/node/bin/* /usr/local/bin/ 2>/dev/null || true


###
### Install Awesome-CI
###
install:
  - ./configure
  - sudo make install


###
### Checks
###
script:

  #------------------------------------------------------------
  # 1.) Validate coding guidelines of self
  #------------------------------------------------------------
  - shellcheck --exclude=SC1090,SC2001 --shell=bash bin/*


  #------------------------------------------------------------
  # 2.) Output Info
  #------------------------------------------------------------
  - make test
