###
### Enable sudo (required for docker service)
###
sudo: required


###
### Use latest node version
###
language: node_js
node_js:
  - node


###
### Before install
###
before_install:
  # Add more modern repos
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository ppa:brightbox/ruby-ng -y
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"

  # Update sources
  - sudo apt-get update -qq

  # Install
  - sudo apt-get install -qq ruby2.3 ruby2.3-dev ruby-switch shellcheck moreutils php5 dos2unix

  # Set ruby version
  #- sudo ruby-switch --set ruby2.3
  - sudo gem update bundler
  - sudo gem pristine executable-hooks --version 1.3.2
  - sudo gem pristine gem-wrappers --version 1.3.2
  - sudo gem pristine nokogiri --version 1.8.1
    #- sudo gem pristine ffi --version 1.9.23

  # Create custom source/bin directory
  - sudo mkdir -p /usr/local/bin
  - sudo mkdir -p /usr/local/src

  # NodeJS4
  - VERSION="$( curl -Lq https://nodejs.org 2>/dev/null | grep LTS | grep -Eo 'data-version.*.' | grep -oE 'v[0-9.]+' )"
  - sudo wget -P /usr/local/src https://nodejs.org/dist/${VERSION}/node-${VERSION}-linux-x64.tar.xz
  - sudo tar xvf /usr/local/src/node-${VERSION}-linux-x64.tar.xz -C /usr/local/src
  - sudo ln -s /usr/local/src/node-${VERSION}-linux-x64 /usr/local/node;
  - sudo ln -s /usr/local/node/bin/* /usr/local/bin/

  - sudo npm install -g eslint
  - sudo npm install -g jsonlint
  - sudo gem install scss_lint
    #- sudo gem install mdl
    #
  - sudo gem install mdl -v 0.3.1

  # Symlink node binaries
  - sudo ln -s /usr/local/node/bin/* /usr/local/bin/ 2>/dev/null || true

  # Install scripts
  - ./configure
  - sudo make install


###
### Checks
###
script:

  #------------------------------------------------------------
  # 1.) Validate coding guidelines of self
  #------------------------------------------------------------
  - shellcheck --exclude=SC1090,SC2001 --shell=bash bin/*


  #------------------------------------------------------------
  # 2.) Output Info
  #------------------------------------------------------------
  - make test
